import random


def guess_number(x):
    print('====================')
    print('Welcome to the game')
    print('====================')
    print ('Your objective is to guess the number generated by the pc')
    
    random_number = random.randint(1,x)
    
    predictor = 0
    
    while predictor != random_number:
        predictor = int(input(f'Guess a number between 1 and {x}: '))
        
        if predictor < random_number:
            print('Try again, your number is lower')
        elif predictor > random_number:
            print ('Try again, your number is higher')
            
    print (f'Congratulations! You guessed the number {random_number} correctly')
    
    
guess_number(10)